#!/bin/bash

echo "🔗 URL con HTTPS (intenta esta primero):"
echo ""
echo "https://accounts.google.com/o/oauth2/v2/auth?client_id=593444311192-7af4l5qv7d765lbr5a3sdesh30efnsd8.apps.googleusercontent.com&redirect_uri=https://localhost:3001/auth/google/callback&scope=https://www.googleapis.com/auth/calendar&response_type=code&access_type=offline&prompt=consent"
echo ""
echo "🔗 URL con HTTP (si la anterior no funciona):"
echo ""
echo "https://accounts.google.com/o/oauth2/v2/auth?client_id=593444311192-7af4l5qv7d765lbr5a3sdesh30efnsd8.apps.googleusercontent.com&redirect_uri=http://localhost:3001/auth/google/callback&scope=https://www.googleapis.com/auth/calendar&response_type=code&access_type=offline&prompt=consent"
echo ""
echo "📋 Pasos:"
echo "1. Intenta primero la URL con HTTPS"
echo "2. Si da error, intenta la URL con HTTP"
echo "3. Copia el código que te devuelva"
echo "4. Pégalo aquí para obtener el Refresh Token"
